# Hugo
DefaultContentLanguage: en
publishdir: public
canonifyUrls: 'true'
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
baseURL: https://xennis.github.io/lifetime-clock-app

title: 'Lifetime Clock App'
params:
  description: 'A clock to visualize your life to encourage making the most out of it.'
  meta:
    author: Xennis
    theme_color: '#efeeff'
    #logo: images/large-logo.png
    google_site_verification: 'NHznC_8EgzaKXrqz1VVGmTUW0HT_5wVyMzAenbxJ7Ro'
  headline:
    screenshots: Screenshots
    description: Description
  footer:
    copyright: Made with ❤️ in Europe 🇪🇺 by <a href="https://github.com/Xennis/" target="_blank">Xennis</a>
    links:
      - title: Github
        url: https://github.com/Xennis/lifetime-clock-app
        target: _blank
      #- title: Donate
      #  url: https://paypal.me/kanbanote
      #  target: _blank
      #- title: Privacy
      #  url: /privacy
  app:
    name: 'Lifetime Clock App'
    description: A clock to visualize your life to encourage making the most out of it.
    full_description: '<p>A clock to visualize your life to encourage making the best out of it.</p>

<p>The app shows you a counter and a graphical box view for your life. You can for example see for how many days you are already alive or how many years are ahead.</p>

<p>Having your lifetime as an app might help you to really make use of your time! Question yourself how you want to spend this time. In the end, it comes down to a matter of priority between all kinds of activities.</p>'
    android: https://play.google.com/store/apps/details?id=org.xennis.apps.lifetime_clock
    screenshots:
      1.png: Screenshot app box view
      2.png: Screenshot app numbers view
      #3.png: Screenshot app numbers view down
      4.png: Screenshot app settings
