name: Flutter
on: push
jobs:
  check-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
    - name: Check format
      run: make format-check
    - name: Run linter
      run: make lint
    - name: Run tests
      run: make test
